openapi: 3.0.0
info:
  version: 1.0.2
  title: Swagger Petstore
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: CONFLICT 2
      operationId: listPets
      tags:
        - pets
      responses:
        '202':
          description: Hello world
  /pets/{petId}:
    get:
      summary: hello
      parameters:
        - name: petId1
          in: path
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
