openapi: 3.0.0
info:
  title: Swagger Petstore
  license:
    name: MIT
paths:
  /pets:
    patch:
      summary: List all pets
      tags:
        - dogs
      responses:
        '201':
          description: Null response
  /newPath2:
    get:
      parameters:
        - name: petId
          schema:
            type: string
