openapi: 3.0.0
info:
  title: The Best Petstore Billing Team API
  version: 1.0.0
  description: An API for The Best Petstore's billing team
servers:
  - url: http://thebestpetstore.com/
paths:
  /billing/chargeCustomer/{customerId}:
    post:
      description: charge a customer with customerId
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: customer charged successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationSuccess"
components:
  schemas:
    OperationSuccess:
      description: a successful operation result
      type: object
      required:
        - billingData
      properties:
        billingData:
          type: string
