openapi: 3.0.0
info:
  title: Swagger Petstore
  license:
    name: MIT
  version: 1.0.2
paths:
  /pets:
    get:
      summary: List all pets
      tags:
        - pets
        - dogs
      responses:
        '201':
          description: Null response
        '202':
          description: Hello world
      operationId: listPets
    post:
      summary: Create a pet
  /pets/{petId}:
    get:
      summary: hello
      parameters:
        - name: petId1
          in: path
        - name: petId2
          in: path2
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /newPath:
    get:
      required: true
      parameters:
        - name: petId
          schema:
            type: string
servers:
  - url: http://petstore.swagger.io/v1
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
