openapi: 3.0.0
info:
  version: 1.0.0
  title: the new and improved petstore
  license:
    name:
      MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: DEFAULT SUMMARY
      operationId: listPets
      tags:
        - pets
        - dogs
      responses:
        '201':
          description: Null response
        '202':
          description: Hello world
    post:
      summary: Create a pet
  /pets/{petId}:
    get:
      summary: hello
      parameters:
        - name: petId1
          in: path
        - name: petId2
          in: path2
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /newPath:
    get:
      parameters:
        - name: petId
          schema:
            type: string
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Dog:
